# Generated by Django 3.0.8 on 2020-07-07 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='tite',
            new_name='title',
        ),
    ]
